version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Docker/Backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:80"
      - "${BACKEND_PORT_SSL}:443"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
    networks:
      server:
      database:
    volumes:
      - "./Logs:/app/Logs"
  adminer:
    build: Docker/Adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db
    networks:
      database:
  db:
    build: Docker/Database
    user: "${POSTGREE_RUN_USER}"
    volumes:
      - "${POSTGREE_VOLUME}:/var/lib/postgresql"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "${POSTGREE_USER}"
      POSTGRES_PASSWORD: "${POSTGREE_PASSWORD}"
      POSTGRES_DB: "${POSTGREE_DB}"
      
    networks:
      database:
      
networks:
  server:
  database:
    
volumes:
  postgree_database: